package com.hanc.test;

/**
 * Created by Administrator on 2016/11/3.
 */
public class Constant
{

    public static String[] Param = {"{\"service\":\"userRechargePage\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"10\"}",
             "{\"service\":\"userRechargeRecordPage\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"10\"}",
            "{\"service\":\"userWithdrawCashPage\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"userWithdrawCashRecordPage\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"demandBorrowPage\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"demandDetailPage\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"demandTenderpage\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"demandTenderAction\",\"demandBorrowID\":\"15\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"10\"}",
            "{\"service\":\"demandBorrowHistoryPage\",\"demandBorrowID\":\"15\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"userTotalAcccountPage\",\"demandBorrowID\":\"15\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"UserBalanceMoneyPage\",\"demandBorrowID\":\"15\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"demandAccountPage\",\"demandBorrowID\":\"15\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"demandTotalIncomePage\",\"demandBorrowID\":\"15\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"demandNormalTotalPage\",\"demandBorrowID\":\"15\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"demandLockTotalPage\",\"demandBorrowID\":\"15\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"userDemandMatch\",\"demandBorrowID\":\"15\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"userDemandMatchDetail\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"15\",\"borrowID\":\"3\"}",
            "{\"service\":\"loadFeelCapitalPage\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"loadDemandTradeRecordPage\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\",\"demandOperateType\":\"TENDER\"}",
            "{\"service\":\"loadDemandRedeemPage\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"yesDemandIncomePage\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"demandRedeemAction\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"userPayMentCalendarPage\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"userProfitBonus\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\",\"status\":\"SUCCESS\"}",
            "{\"service\":\"userCashBonus\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\",\"status\":\"SUCCESS\"}",
            "{\"service\":\"userFeelMoney\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\",\"status\":\"DOING\"}",
            "{\"service\":\"userFeelMoney\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\",\"status\":\"INIT\"}",
            "{\"service\":\"userWithdrawCashCard\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"5\",\"status\":\"USE\"}",
            "{\"service\":\"userWithdrawCashCard\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"5\",\"status\":\"USED\"}",
            "{\"service\":\"userGiftBox\",\"demandBorrowID\":\"3\",\"lockCardID\":\"1\",\"operateMoney\":\"1000\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"5\",\"tenderld\":\"1\"}",
            "{\"service\":\"userBorrowTenderDetail\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"page\":\"1\",\"rows\":\"1\",\"tenderId\":\"1\"}",
            "{\"service\":\"userSetting\",\"lockCardID\":\"1\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\"}",
            "{\"service\":\"index\",\"userId\":\"1\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"Page\":1,\"rows\":3}",
            "{\"service\":\"queryBorrowList\",\"borrowId\":\"1\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"Page\":\"1\",\"rows\":\"1\"}",
            "{\"service\":\"selectBorrowDetailById\",\"borrowId\":\"1\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\"}",
            "{\"service\":\"loadProjectDetailByBorrowIdOrType\",\"borrowId\":\"1\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\",\"type\":\"NORMAL \"}",
            "{\"service\":\"loadProjectPicDataByOwnerId\",\"ownerId\":\"1\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\"}",
            "{\"service\":\"loadBorrowTenderList\",\"borrowId\":\"1\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\"}",
            "{\"service\":\"borrowTenderListPage\",\"borrowId\":\"1\",\"userId\":\"1\",\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"order_no\":\"sdfsddf\"}",
            "{\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"tenderAction\",\"order_no\":\"sdfsddf\",\"borrowId\":\"1\",\"userId\":\"1\",\"tenderMoney\":\"10000\",\"ip\":\"192.168.0.1\",\"profitBonusId\":\"1\",\"type\":\"NORMAL \"}",
            "{\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"loadUserAccountPage\",\"order_no\":\"sdfsddf\"}",
            "{\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"accountRecordList\",\"order_no\":\"sdfsddf\",\"startDate\":\"2016-05-01\",\"endDate\":\"2016-10-18\",\"Page\":\"1\",\"rows\":\"15\"}",
            "{\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"userOtherGift\",\"order_no\":\"sdfsddf\",\"Page\":\"1\",\"rows\":\"5\"}",
            "{\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"userAutoTenderPage\",\"order_no\":\"sdfsddf\"}",
            "{\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"saveAutoTender\",\"order_no\":\"sdfsddf\",\"status\":\"OPEN \",\"minTenderMoney\":\"100\",\"maxTenderMoney\":\"1000\",\"minTimelimit\":\"3\",\"maxTimelimit\":\"9\",\"repayTypes\":\"1,2,3\"}",
            "{\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"borrowAgreement\",\"order_no\":\"sdfsddf\",\"borrowId\":\"1 \"}",
            "{\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"borrowInterestCalcution\",\"order_no\":\"sdfsddf\",\"borrowId\":\"1 \",\"operateMoney\":\"200000\"}",
            "{\"token\":\"AAAAAA\",\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"borrowRecommand\",\"order_no\":\"sdfsddf\",\"profitBonusId\":\"1 \"}",
            "{\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"login\",\"order_no\":\"sdfsddf\",\"phone\":\"15853122079\",\"password\":\"123456\"}",
            "{\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"register\",\"order_no\":\"sdfsddf\",\"phone\":\"15853122078\",\"password\":\"123456\",\"inviteCode\":\"\",\"validCode\":\"123456\"}",
            "{\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"loadModifyUserPhonePage\",\"order_no\":\"sdfsddf\",\"token\":\"AAAAAA\"}",
            "{\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"validUserCardId\",\"order_no\":\"sdfsddf\",\"cardId\":\"331004188811111818\",\"token\":\"AAAAAA\"}",
            "{\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"sendPhoneSms\",\"order_no\":\"sdfsddf\",\"phone\":\"15853122079\",\"token\":\"AAAAAA\",\"type\":\"1\"}",
            "{\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"loadModifyUserPhonePage\",\"order_no\":\"sdfsddf\",\"phone\":\"15158565854\",\"token\":\"AAAAAA\",\"validCode\":\"236854\"}",
            "{\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"realnameValid\",\"order_no\":\"sdfsddf\",\"cardId\":\"331004188811111818\",\"token\":\"AAAAAA\",\"realname\":\"张小王\"}",
            "{\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"setPayPassword\",\"order_no\":\"sdfsddf\",\"token\":\"AAAAAA\"}",
            "{\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"modifyPayPassword\",\"order_no\":\"sdfsddf\",\"token\":\"AAAAAA\"}",
            "{\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"findPayPassword \",\"order_no\":\"sdfsddf\",\"token\":\"AAAAAA\"}",
            "{\"version\":\"1.0\",\"os\":\"ios\",\"service\":\"handleWithholdAuthority\",\"order_no\":\"sdfsddf\",\"token\":\"AAAAAA\"}"


    };
    public static int[] hashList = {363968591,-1000640716,-1123992643,-392736167,-1131169818,
            490619550,-1348026140,1386339995,-1396017071,-2017325069,-17136800,1239277836,-271602925,
            43208979,-209082731,782961742,769650955,152295084,-163491119,2034545095,-479426612,1367339648,
            68688520,-1841671378,-1188019570,-368176140,-759989911,566595531,813970174,1897334443,1354489635,
            -1107755715};
}
